### ISSUE TITLE
Bad wallet error

### ISSUE THREAD

**Issue by hairtail** [virdpool/miner#24]
hi, vird
I get one problem when start to mine arweave with proxy.coffee script. I use same script and absolutely same wallet address in 3 machines, but now I get this error in one of them while other 2 machines work well.
you can check error log here.
```
2022-03-04T08:37:54.839Z [Error: bad wallet
  at Websocket_wrap.<anonymous> (/home/ps/arweave/script/node_modules/wsrs/lib/index.js:26:20)
  at Websocket_wrap._t.dispatch (/home/ps/arweave/script/node_modules/event_mixin/lib/index.js:120:16)
  at WebSocket.<anonymous> (/home/ps/arweave/script/node_modules/ws_wrap/lib/index.js:117:17)
  at WebSocket.onMessage (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/EventTarget.js:99:16)
  at WebSocket.emit (events.js:400:28)
  at Receiver._receiver.onmessage (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/WebSocket.js:141:47)
  at Receiver.dataMessage (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/Receiver.js:389:14)
  at Receiver.getData (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/Receiver.js:330:12)
  at Receiver.startLoop (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/Receiver.js:165:16)
  at Receiver.add (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/Receiver.js:139:10)
  at Socket.<anonymous> (/home/ps/arweave/script/node_modules/ws_wrap/node_modules/ws/lib/WebSocket.js:138:22)
  at Socket.emit (events.js:400:28)
  at addChunk (internal/streams/readable.js:293:12)
  at readableAddChunk (internal/streams/readable.js:267:9)
  at Socket.Readable.push (internal/streams/readable.js:206:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
]
```

**Comment by hairtail** [comment]
look forward to your reply

**Comment by vird** [comment]
bad wallet means ... that you specified bad wallet. It should be base64url 43 chars
Can you tell your address?

**Comment by hairtail** [comment]
it's weird. I use the same script(of course same address) in many machines,
just one or two of them met this error.

vird ***@***.***> 于2022年3月13日周日 17:56写道：

**Comment by vird** [comment]
Can you try another your address on that machine?

**Comment by hairtail** [comment]
> 



> Can you try another your address on that machine?

sure, it works
